### ISSUE TITLE
Registry UI does not remove database lock on stop/shutdown

### ISSUE THREAD

**Issue by mgingell** [atc-/docker-registry-ui#142]
I have deployed the registry ui container using compose as follows:
```
registryui:
  image: atcol/docker-registry-ui
  ports:
    - "8085:8080"
  links:
    - registry:registry
  environment:
    - REG1=http://registry:5000/v1/
  volumes:
   - /opt/docker-registry-ui/data:/var/lib/h2
  restart: always
```
As you can see, I am using a host mounted volume for persistence.  When I stop the container:
`docker-compose stop`
The database lock remains in the host mounted volume.  This prevents the container from restarting correctly the next time around due to failure to acquire the DB lock.  My workaround is to delete the lockfile and then restart the container, but I try to have the services restart always, so this prevents this from happening.
Thanks for the UI tool!  It is very useful, I'm looking forward to using it with the new registry API!
 - Mike
